# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import broker_pb2 as broker__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produce = channel.unary_unary(
                '/broker.BrokerService/Produce',
                request_serializer=broker__pb2.ProduceRequest.SerializeToString,
                response_deserializer=broker__pb2.ProduceResponse.FromString,
                _registered_method=True)
        self.Consume = channel.unary_unary(
                '/broker.BrokerService/Consume',
                request_serializer=broker__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=broker__pb2.ConsumeResponse.FromString,
                _registered_method=True)
        self.CommitOffset = channel.unary_unary(
                '/broker.BrokerService/CommitOffset',
                request_serializer=broker__pb2.CommitOffsetRequest.SerializeToString,
                response_deserializer=broker__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCommittedOffset = channel.unary_unary(
                '/broker.BrokerService/GetCommittedOffset',
                request_serializer=broker__pb2.GetCommittedOffsetRequest.SerializeToString,
                response_deserializer=broker__pb2.CommittedOffsetResponse.FromString,
                _registered_method=True)
        self.ConsumeStream = channel.unary_stream(
                '/broker.BrokerService/ConsumeStream',
                request_serializer=broker__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=broker__pb2.ConsumeResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/broker.BrokerService/Subscribe',
                request_serializer=broker__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=broker__pb2.Empty.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Produce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommittedOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Produce': grpc.unary_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=broker__pb2.ProduceRequest.FromString,
                    response_serializer=broker__pb2.ProduceResponse.SerializeToString,
            ),
            'Consume': grpc.unary_unary_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=broker__pb2.ConsumeRequest.FromString,
                    response_serializer=broker__pb2.ConsumeResponse.SerializeToString,
            ),
            'CommitOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOffset,
                    request_deserializer=broker__pb2.CommitOffsetRequest.FromString,
                    response_serializer=broker__pb2.Empty.SerializeToString,
            ),
            'GetCommittedOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommittedOffset,
                    request_deserializer=broker__pb2.GetCommittedOffsetRequest.FromString,
                    response_serializer=broker__pb2.CommittedOffsetResponse.SerializeToString,
            ),
            'ConsumeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ConsumeStream,
                    request_deserializer=broker__pb2.ConsumeRequest.FromString,
                    response_serializer=broker__pb2.ConsumeResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=broker__pb2.SubscribeRequest.FromString,
                    response_serializer=broker__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.BrokerService/Produce',
            broker__pb2.ProduceRequest.SerializeToString,
            broker__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.BrokerService/Consume',
            broker__pb2.ConsumeRequest.SerializeToString,
            broker__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.BrokerService/CommitOffset',
            broker__pb2.CommitOffsetRequest.SerializeToString,
            broker__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommittedOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.BrokerService/GetCommittedOffset',
            broker__pb2.GetCommittedOffsetRequest.SerializeToString,
            broker__pb2.CommittedOffsetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.BrokerService/ConsumeStream',
            broker__pb2.ConsumeRequest.SerializeToString,
            broker__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.BrokerService/Subscribe',
            broker__pb2.SubscribeRequest.SerializeToString,
            broker__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
